const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function createPreviewApprovedRepository(options = {}) { const env = options.env || process.env; const fetchImpl = options.fetchImpl || global.fetch; return { findTestJourney: (id) => find(id, env, fetchImpl), applyProgress: (instance, transition) => apply(instance, transition, env, fetchImpl), enableTestJourney: (id) => enable(id, env, fetchImpl) }; }
async function find(customerId, env, fetchImpl) { if (!UUID.test(String(customerId || ""))) return { available: true, row: null, reason: "invalid_customer_id" }; const config = cfg(env); if (!config.available) return unavailable("missing_supabase_config"); try { const query = new URLSearchParams({ select: "id,instance_key,customer_id,current_phase,current_step,progress_percent,status,environment,metadata,updated_at", customer_id: `eq.${customerId}`, environment: "eq.test", status: "eq.active", order: "updated_at.desc", limit: "10" }); const rows = await request(fetchImpl, `${config.url}/rest/v1/journey_instances?${query}`, { headers: headers(config.key) }); return { available: true, row: (rows || []).find((row) => row.metadata?.testOnly === true && row.metadata?.previewApprovedEmailOwner === "journey") || null }; } catch { return unavailable("storage_read_failed"); } }
async function apply(instance, transition, env, fetchImpl) { if (!instance?.id || !transition?.patch) return { available: true, skipped: true, reason: transition?.duplicate ? "duplicate_progress" : "progress_patch_missing" }; const config = cfg(env); if (!config.available) return unavailable("missing_supabase_config"); const query = new URLSearchParams({ id: `eq.${instance.id}` }); if (instance.updated_at) query.set("updated_at", `eq.${instance.updated_at}`); try { const rows = await request(fetchImpl, `${config.url}/rest/v1/journey_instances?${query}`, { method: "PATCH", headers: { ...headers(config.key), "Content-Type": "application/json", Prefer: "return=representation" }, body: JSON.stringify({ ...transition.patch, updated_at: new Date().toISOString() }) }); return rows?.[0] ? { available: true, skipped: false, reason: "progress_updated", row: rows[0] } : { available: false, skipped: true, reason: "progress_write_conflict" }; } catch { return { available: false, skipped: true, reason: "progress_write_failed" }; } }
async function enable(customerId, env, fetchImpl) { if (!UUID.test(String(customerId || ""))) throw error("invalid_customer_id", 400); const config = cfg(env); if (!config.available) return unavailable("missing_supabase_config"); const query = new URLSearchParams({ select: "id,instance_key,status,environment,metadata,updated_at", customer_id: `eq.${customerId}`, environment: "eq.test", status: "eq.active", order: "updated_at.desc", limit: "1" }); const rows = await request(fetchImpl, `${config.url}/rest/v1/journey_instances?${query}`, { headers: headers(config.key) }); const instance = rows?.[0]; if (!instance?.id || instance.metadata?.testOnly !== true) return { available: true, row: null, reason: "test_journey_missing" }; const patch = new URLSearchParams({ id: `eq.${instance.id}` }); if (instance.updated_at) patch.set("updated_at", `eq.${instance.updated_at}`); const saved = await request(fetchImpl, `${config.url}/rest/v1/journey_instances?${patch}`, { method: "PATCH", headers: { ...headers(config.key), "Content-Type": "application/json", Prefer: "return=representation" }, body: JSON.stringify({ metadata: { ...instance.metadata, previewApprovedEmailOwner: "journey", previewApprovedTestOnly: true }, updated_at: new Date().toISOString() }) }); return { available: true, row: saved?.[0] || null, reason: "approval_test_enabled" }; }
async function request(fetchImpl, url, options = {}) { const response = await fetchImpl(url, options); const text = await response.text(); let body; try { body = text ? JSON.parse(text) : null; } catch { throw error("invalid_response", 502); } if (!response.ok) throw error(String(body?.code || "request_failed"), response.status); return body; }
function cfg(env) { const url = String(env.SUPABASE_URL || "").replace(/\/$/, ""); const key = String(env.SUPABASE_SERVICE_ROLE_KEY || "").trim(); return { available: Boolean(/^https:\/\/[^/]+\.supabase\.co$/i.test(url) && key), url, key }; }
function headers(key) { return { apikey: key, Authorization: `Bearer ${key}`, Accept: "application/json", "Accept-Profile": "public", "Content-Profile": "public" }; }
function unavailable(reason) { return { available: false, row: null, reason }; }
function error(code, statusCode) { return Object.assign(new Error("Approval journey storage failed."), { code, statusCode }); }
module.exports = { createPreviewApprovedRepository };
