const { createHash } = require("crypto");
const { createJourneyRepository } = require("../repository");
const { createJourneyLogger } = require("../logger");
const { validateMailCommand } = require("../mail/command");
const { resolveApprovalOwnership } = require("./ownershipResolver");
const { planApprovalProgress } = require("./progressTransition");
const { createPreviewApprovedRepository } = require("./repository");
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function createPreviewApprovedService(options = {}) { const env = options.env || process.env; const journeyRepository = options.journeyRepository || createJourneyRepository(options); const approvalRepository = options.approvalRepository || createPreviewApprovedRepository(options); const log = options.log || createJourneyLogger({ logger: options.logger, component: "preview_approved_ownership" }); return { dispatch: (input) => dispatch(input, env, journeyRepository, approvalRepository, log) }; }
async function dispatch(input = {}, env, journeyRepository, approvalRepository, log) {
  const legacy = typeof input.legacySend === "function" ? input.legacySend : async () => null;
  const customerId = text(input.customerId); const previewVersionId = text(input.previewVersionId); const approvalReference = text(input.approvalReference);
  if (!text(input.recipient)) return base("none", "recipient_missing");
  if (![customerId, previewVersionId].every((value) => UUID.test(value)) || !approvalReference) return legacyResult(legacy, "stable_approval_scope_missing");
  const runtimeEnvironment = runtime(env); const resolution = input.resolution || {};
  const preflight = resolveApprovalOwnership({ ...input, customerId, previewVersionId, resolution, runtimeEnvironment, journeyInstance: null, transition: null }, env);
  if (preflight.reason !== "test_journey_missing") return legacyResult(legacy, preflight.reason);
  let lookup; try { lookup = await approvalRepository.findTestJourney(customerId); } catch { lookup = { available: false, reason: "storage_read_failed" }; }
  if (!lookup?.available) return legacyResult(legacy, lookup?.reason || "storage_unavailable");
  const reference = fingerprint(approvalReference); const transition = planApprovalProgress(lookup.row || {}, reference, resolution);
  const ownership = resolveApprovalOwnership({ ...input, customerId, previewVersionId, resolution, runtimeEnvironment, journeyInstance: lookup.row, transition }, env);
  const keys = stableKeys({ customerId, previewVersionId, approvalReference, templateVersion: 1 });
  if (ownership.owner !== "journey") return ownership.owner === "none" ? base("none", ownership.reason) : legacyResult(legacy, ownership.reason);
  let command;
  try { command = validateMailCommand({ automationKey: "journey.preview_approved", templateKey: "journey.preview_approved", templateVersion: 1, journeyEventKey: keys.eventKey, outboxIdempotencyKey: keys.outboxKey, customerReference: customerId, journeyInstanceReference: lookup.row.id, recipient: input.recipient, replyToProfile: { email: "info@maxwebstudio.nl" }, subjectData: { label: text(input.projectLabel) || "uw website" }, templateData: { firstName: text(input.firstName), projectLabel: text(input.projectLabel) || "uw website", previewVersionLabel: text(input.previewVersionLabel) || "Website-preview", percentage: transition.after.percentage, currentPhase: transition.after.currentPhase || "Vervolgstap", nextStepType: resolution.nextStepType, paymentState: resolution.paymentState, invoiceState: resolution.invoiceState, customerActionRequired: resolution.customerActionRequired === true, internalActionRequired: resolution.internalActionRequired === true, nextStep: copyFor(resolution.nextStepType), contactName: text(input.contactName) || "Team Max Webstudio" }, actionUrl: resolution.cta || "", metadata: { scenario: "preview_approved_test_customer", previewVersionReference: previewVersionId, approvalReference: reference } }, { customerId, journeyInstanceId: lookup.row.id, environment: "test" }, env); } catch (error) { log.info("approval_validation_fallback", { operation: "preview_approved_dispatch", result: "legacy", owner: "legacy", errorCategory: code(error), testMode: true }); return legacyResult(legacy, code(error)); }
  try {
    const stored = await journeyRepository.recordJourneyEvent({ eventKey: keys.eventKey, eventType: "preview.approved", entityType: "preview", entityId: previewVersionId, customerId, journeyInstanceId: lookup.row.id, environment: "test", occurredAt: safeDate(input.approvedAt), payload: { source: "client_preview_versions", testMode: true, ownership: "journey", ownershipReason: ownership.reason, previewVersionReference: previewVersionId, approvalReference: reference, journeyType: resolution.journeyType, nextStepType: resolution.nextStepType, paymentState: resolution.paymentState, invoiceState: resolution.invoiceState, customerActionRequired: resolution.customerActionRequired === true, internalActionRequired: resolution.internalActionRequired === true, progressBefore: transition.before.percentage, progressAfter: transition.after.percentage } }, { context: { customerId, journeyInstanceId: lookup.row.id, journeyKey: lookup.row.instance_key, entityId: previewVersionId, environment: "test" }, outbox: { idempotencyKey: keys.outboxKey, effectType: "email.preview_approved", payload: { mailCommand: command, ownership: "journey", ownershipReason: ownership.reason, previewVersionReference: previewVersionId, approvalReference: reference, journeyType: resolution.journeyType, nextStepType: resolution.nextStepType, paymentState: resolution.paymentState, invoiceState: resolution.invoiceState, customerActionRequired: resolution.customerActionRequired === true, internalActionRequired: resolution.internalActionRequired === true, progressBefore: transition.before.percentage, progressAfter: transition.after.percentage } } });
    if (!stored?.available) return legacyResult(legacy, stored?.reason || "storage_unavailable");
    if (!stored?.row?.outbox_id) throw Object.assign(new Error("outbox unavailable"), { code: "outbox_not_created" });
    let progress = { updated: false, reason: transition.duplicate ? "duplicate_progress" : "progress_not_attempted" }; try { const update = await approvalRepository.applyProgress(lookup.row, transition); progress = { updated: Boolean(update?.available && !update?.skipped), reason: update?.reason || "progress_write_failed" }; } catch { progress.reason = "progress_write_failed"; }
    return { ...base("journey", stored.row.duplicate ? "duplicate_suppressed" : "journey_outbox_accepted"), durable: true, fallbackAllowed: false, duplicate: Boolean(stored.row.duplicate), eventKey: keys.eventKey, outboxId: stored.row.outbox_id, approvalReference: reference, progress };
  } catch (error) { log.error("approval_journey_enqueue_failed", { operation: "preview_approved_dispatch", result: "failed", owner: "journey", errorCategory: code(error), testMode: true }); return { ...base("journey", "journey_enqueue_ambiguous_no_legacy"), fallbackAllowed: false, failed: true, eventKey: keys.eventKey, approvalReference: reference }; }
}
function stableKeys({ customerId, previewVersionId, approvalReference, templateVersion }) { const scope = hash(`${customerId}:${previewVersionId}:${approvalReference}:email.preview_approved:v${templateVersion}`); return { eventKey: `preview.approved:${scope}`, outboxKey: `preview.approved.email:${scope}:v${templateVersion}` }; }
function copyFor(type) { return ({ technical_completion: "Wij gaan verder met de technische afronding. U hoeft nu niets te betalen.", approval_processing: "Wij verwerken de goedkeuring en controleren de afgesproken vervolgstap.", existing_invoice: "De bestaande factuur staat veilig klaar in het klantportaal.", commercial_confirmation: "Bevestig de commerciële opdracht om het project definitief te starten.", commercial_review: "Team Max Webstudio controleert de administratieve vervolgstap.", financial_review: "Team Max Webstudio controleert de administratieve vervolgstap.", already_live: "De goedkeuring is vastgelegd; er is geen aanvullende actie nodig." })[type] || "Team Max Webstudio controleert de vervolgstap."; }
async function legacyResult(fn, reason) { await fn(); return base("legacy", reason); }
function base(owner, reason) { return { owner, reason, durable: false, eligibility: owner === "journey" ? "eligible" : "ineligible", fallbackAllowed: owner === "legacy", duplicate: false, failed: false, testMode: true, eventKey: null }; }
function safeDate(value) { const date = new Date(value || Date.now()); return Number.isNaN(date.getTime()) ? new Date().toISOString() : date.toISOString(); }
function runtime(env) { return [env.APP_ENV, env.APP_ENVIRONMENT, env.CONTEXT, env.NETLIFY_ENV].some((value) => ["prod", "production"].includes(text(value).toLowerCase())) ? "production" : "test"; }
function fingerprint(value) { return hash(value).slice(0, 16); } function hash(value) { return createHash("sha256").update(String(value || "")).digest("hex").slice(0, 40); }
function code(error) { return text(error?.code || error?.name || "approval_dispatch_failed").replace(/[^a-z0-9_.-]/gi, "_").slice(0, 80).toLowerCase(); }
function text(value) { return String(value || "").trim(); }
module.exports = { createPreviewApprovedService, _private: { fingerprint, stableKeys } };
