export const CATEGORY_PROFILES = {
  bouw: {
    tone: "vakkundig, betrouwbaar, concreet en resultaatgericht",
    audience: "particulieren en bedrijven die degelijk vakwerk en heldere afspraken zoeken",
    palette: ["#15202B", "#31513D", "#D49A3A", "#F4F1E9"],
    fonts: ["Manrope", "Source Serif 4"],
    visualStyle: "authentieke Nederlandse vakmensen, hoogwaardige materialen, zichtbaar eindresultaat",
    servicePatterns: ["Advies en opname", "Nieuwbouw", "Renovatie", "Reparatie", "Onderhoud", "Spoedservice", "Inspectie", "Maatwerk", "Zakelijke projecten", "Particuliere projecten", "Duurzame oplossingen", "Nazorg"],
  },
  mobiliteit: {
    tone: "direct, deskundig, betrouwbaar en servicegericht",
    audience: "mensen en organisaties die veilig, snel en zorgeloos onderweg willen zijn",
    palette: ["#101820", "#244C5A", "#11AFA0", "#F3F6F5"],
    fonts: ["Barlow", "Inter"],
    visualStyle: "dynamische mobiliteitsfotografie, moderne werkplaats, echte medewerkers, heldere details",
    servicePatterns: ["Advies", "Aankoop", "Verkoop", "Onderhoud", "Reparatie", "Diagnose", "Verhuur", "Pechservice", "Zakelijk aanbod", "Inruil", "Aflevering", "Nazorg"],
  },
  zakelijk: {
    tone: "helder, deskundig, integer en persoonlijk",
    audience: "ondernemers en particulieren die zekerheid, overzicht en deskundig advies zoeken",
    palette: ["#101827", "#1E4770", "#C6A15B", "#F5F7FA"],
    fonts: ["DM Sans", "Libre Baskerville"],
    visualStyle: "rustige premium kantooromgeving, geloofwaardige professionals, natuurlijk daglicht",
    servicePatterns: ["Kennismaking", "Strategisch advies", "Analyse", "Uitvoering", "Begeleiding", "Second opinion", "Periodieke controle", "Rapportage", "Zakelijke ondersteuning", "Particuliere ondersteuning", "Online consult", "Nazorg"],
  },
  digitaal: {
    tone: "slim, toegankelijk, vooruitstrevend en resultaatgericht",
    audience: "organisaties die digitaal willen groeien, automatiseren en professionaliseren",
    palette: ["#101828", "#4F46E5", "#22C1C3", "#F4F5FF"],
    fonts: ["Space Grotesk", "Inter"],
    visualStyle: "moderne digitale studio, abstracte datalagen, echte samenwerking, premium technologie",
    servicePatterns: ["Strategie", "Audit", "Ontwerp", "Implementatie", "Integraties", "Automatisering", "Optimalisatie", "Beheer", "Support", "Training", "Rapportage", "Doorontwikkeling"],
  },
  beauty: {
    tone: "warm, stijlvol, persoonlijk en uitnodigend",
    audience: "klanten die verzorging, ontspanning en een resultaat dat bij hen past zoeken",
    palette: ["#241B22", "#8A5E70", "#D7B28B", "#FAF5F3"],
    fonts: ["Cormorant Garamond", "Manrope"],
    visualStyle: "editorial beautyfotografie, zachte texturen, echte behandeling, warm natuurlijk licht",
    servicePatterns: ["Kennismaking", "Advies", "Basisbehandeling", "Premium behandeling", "Combinatiebehandeling", "Express behandeling", "Arrangement", "Bruidsservice", "Productadvies", "Cadeaubon", "Onderhoud", "Nazorg"],
  },
  gezondheid: {
    tone: "rustig, deskundig, menselijk en zorgvuldig",
    audience: "mensen die verantwoord willen werken aan gezondheid, herstel en welzijn",
    palette: ["#18302B", "#357468", "#A8C7B8", "#F4F8F6"],
    fonts: ["Lora", "Inter"],
    visualStyle: "lichte professionele praktijk, menselijke begeleiding, rustige compositie, authentieke zorg",
    servicePatterns: ["Intake", "Onderzoek", "Persoonlijk behandelplan", "Behandeling", "Preventie", "Herstelbegeleiding", "Online consult", "Groepsprogramma", "Controle", "Advies", "Doorverwijzing", "Nazorg"],
  },
  horeca: {
    tone: "sfeervol, gastvrij, smaakvol en uitnodigend",
    audience: "gasten die sfeer, kwaliteit en een soepel bezoek of verblijf zoeken",
    palette: ["#251A15", "#763C2F", "#D3A257", "#FBF4E9"],
    fonts: ["Playfair Display", "DM Sans"],
    visualStyle: "cinematische hospitalityfotografie, rijke details, echte gasten, warm avondlicht",
    servicePatterns: ["Reserveren", "Regulier aanbod", "Seizoensaanbod", "Arrangementen", "Groepen", "Zakelijke boekingen", "Privé-evenementen", "Afhalen", "Bezorgen", "Catering", "Cadeaubon", "Speciale wensen"],
  },
  sport: {
    tone: "energiek, motiverend, inclusief en doelgericht",
    audience: "beginners en ervaren sporters die plezier, progressie en verbinding zoeken",
    palette: ["#111827", "#176B5B", "#E6A817", "#F3F6F5"],
    fonts: ["Oswald", "Inter"],
    visualStyle: "energiek sportmoment, echte deelnemers, beweging bevroren, krachtige lichtval",
    servicePatterns: ["Proefles", "Training", "Vrij sporten", "Jeugd", "Volwassenen", "Competitie", "Privéles", "Groepsles", "Clinics", "Evenementen", "Lidmaatschap", "Coaching"],
  },
  retail: {
    tone: "inspirerend, behulpzaam, eigentijds en betrouwbaar",
    audience: "consumenten die kwaliteit, persoonlijk advies en een prettige koopervaring waarderen",
    palette: ["#171717", "#3E5B54", "#D38B5D", "#F7F4EF"],
    fonts: ["Montserrat", "Merriweather"],
    visualStyle: "premium productfotografie, verzorgde winkelomgeving, menselijke service, tactiele details",
    servicePatterns: ["Collectie", "Persoonlijk advies", "Online bestellen", "Winkelbezoek", "Maatwerk", "Reparatie", "Onderhoud", "Inruil", "Zakelijke bestelling", "Cadeaus", "Bezorging", "Klantenservice"],
  },
  recreatie: {
    tone: "enthousiast, ontspannen, duidelijk en avontuurlijk",
    audience: "vrienden, gezinnen en teams die samen een verzorgde ervaring willen beleven",
    palette: ["#102A43", "#147D92", "#F0A43C", "#F4FAFB"],
    fonts: ["Poppins", "Inter"],
    visualStyle: "levendige ervaringsfotografie, echte deelnemers, brede omgeving, zonnig natuurlijk licht",
    servicePatterns: ["Boeken", "Los bezoek", "Arrangement", "Groepen", "Bedrijfsuitje", "Kinderfeestje", "Verhuur", "Instructie", "Seizoensaanbod", "Catering", "Cadeaubon", "Praktische informatie"],
  },
  media: {
    tone: "creatief, scherp, beeldend en professioneel",
    audience: "merken en mensen die een krachtig verhaal en onderscheidende zichtbaarheid willen",
    palette: ["#151515", "#523B77", "#E85D75", "#F7F4FA"],
    fonts: ["Sora", "Inter"],
    visualStyle: "editorial contentproductie, creatieve studio, behind-the-scenes, cinematografisch contrast",
    servicePatterns: ["Concept", "Voorbereiding", "Productie", "Portret", "Bedrijfsreportage", "Campagne", "Evenement", "Productcontent", "Nabewerking", "Contentpakket", "Licentie", "Oplevering"],
  },
  lokaal: {
    tone: "vriendelijk, professioneel, praktisch en lokaal betrokken",
    audience: "lokale klanten die snel duidelijkheid en betrouwbare service zoeken",
    palette: ["#132238", "#2563EB", "#14B8A6", "#F6F8FB"],
    fonts: ["Manrope", "Inter"],
    visualStyle: "authentieke lokale onderneming, echte medewerkers, herkenbare omgeving, helder daglicht",
    servicePatterns: ["Kennismaking", "Advies", "Basisservice", "Uitgebreide service", "Maatwerk", "Spoed", "Onderhoud", "Periodieke service", "Zakelijke service", "Particuliere service", "Controle", "Nazorg"],
  }
};

const V = (slug, name, category, singular, primaryService, related = []) => ({
  slug, name, category, singular, primaryService, related
});

export const VERTICALS = [
  V("bouw", "Bouwbedrijf", "bouw", "bouwer", "Bouw en renovatie", ["verbouwing", "nieuwbouw", "woningrenovatie"]),
  V("aannemer", "Aannemer", "bouw", "aannemer", "Aanneming en verbouw", ["aanbouw", "renovatie", "bouwbegeleiding"]),
  V("schilder", "Schildersbedrijf", "bouw", "schilder", "Binnen- en buitenschilderwerk", ["houtrot", "wandafwerking", "onderhoudsschilderwerk"]),
  V("dakdekker", "Dakdekker", "bouw", "dakdekker", "Dakwerk en dakonderhoud", ["dakreparatie", "dakinspectie", "dakrenovatie"]),
  V("loodgieter", "Loodgieter", "bouw", "loodgieter", "Loodgieterswerk", ["lekkage", "sanitair", "leidingwerk"]),
  V("elektricien", "Elektricien", "bouw", "elektricien", "Elektra en storingen", ["groepenkast", "laadpaal", "elektrakeuring"]),
  V("installateur", "Installatiebedrijf", "bouw", "installateur", "Installatie en onderhoud", ["warmtepomp", "cv-ketel", "verduurzaming"]),
  V("glazenwasser", "Glazenwasser", "bouw", "glazenwasser", "Glasbewassing", ["gevelreiniging", "periodieke reiniging", "vve"]),
  V("schoonmaak", "Schoonmaakbedrijf", "bouw", "schoonmaakspecialist", "Professionele schoonmaak", ["kantoor", "oplevering", "vve"]),
  V("beveiliging", "Beveiligingsbedrijf", "bouw", "beveiligingsspecialist", "Beveiliging en toezicht", ["camerabeveiliging", "alarm", "objectbeveiliging"]),
  V("hovenier", "Hovenier", "bouw", "hovenier", "Tuinontwerp en aanleg", ["tuinonderhoud", "bestrating", "beplanting"]),
  V("tegelzetter", "Tegelzetbedrijf", "bouw", "tegelzetter", "Wand- en vloertegelwerk", ["badkamertegels", "natuursteen", "voegwerk"]),
  V("stukadoor", "Stukadoorsbedrijf", "bouw", "stukadoor", "Stucwerk en wandafwerking", ["spachtelputz", "plafond", "gevelstuc"]),
  V("badkamers", "Badkamerspecialist", "bouw", "badkamerspecialist", "Badkamerontwerp en renovatie", ["sanitair", "inloopdouche", "badkamermeubel"]),
  V("keukens", "Keukenspecialist", "bouw", "keukenspecialist", "Keukenontwerp en montage", ["maatwerkkeuken", "keukenrenovatie", "apparatuur"]),
  V("timmerwerk", "Timmerbedrijf", "bouw", "timmerman", "Timmerwerk en maatwerk", ["zolder", "overkapping", "kozijnen"]),
  V("kozijnen", "Kozijnenspecialist", "bouw", "kozijnspecialist", "Kozijnen en deuren", ["kunststof kozijnen", "hout", "isolatie"]),
  V("vloerenspecialist", "Vloerenspecialist", "bouw", "vloerenspecialist", "Vloeren en afwerking", ["pvc", "parket", "gietvloer"]),
  V("zonnepanelen", "Zonnepanelenspecialist", "bouw", "energiespecialist", "Zonnepanelen en energie", ["thuisbatterij", "omvormer", "monitoring"]),
  V("graafmachineverhuur", "Graafmachineverhuur", "bouw", "verhuurspecialist", "Graafmachines en materieel", ["minigraver", "shovel", "grondverzet"]),

  V("autobedrijf", "Autobedrijf", "mobiliteit", "autospecialist", "Auto-onderhoud en verkoop", ["apk", "occasions", "diagnose"]),
  V("occasions", "Occasiondealer", "mobiliteit", "autodealer", "Occasions", ["inruil", "proefrit", "garantie"]),
  V("garage", "Autogarage", "mobiliteit", "automonteur", "Onderhoud en reparatie", ["apk", "diagnose", "banden"]),
  V("carwash", "Carwash", "mobiliteit", "carwashspecialist", "Autowassen en detailing", ["interieurreiniging", "poetsen", "abonnement"]),
  V("fietswinkel", "Fietswinkel", "mobiliteit", "fietsspecialist", "Fietsen en onderhoud", ["e-bike", "reparatie", "fietsmeting"]),
  V("scooters", "Scooterwinkel", "mobiliteit", "scooterspecialist", "Scooters en onderhoud", ["elektrische scooter", "reparatie", "onderdelen"]),
  V("motoren", "Motorzaak", "mobiliteit", "motorspecialist", "Motoren en service", ["occasions", "onderhoud", "motorkleding"]),
  V("boten", "Botenbedrijf", "mobiliteit", "botenspecialist", "Boten en onderhoud", ["verkoop", "winterstalling", "reparatie"]),
  V("transport", "Transportbedrijf", "mobiliteit", "transportspecialist", "Nationaal en internationaal transport", ["distributie", "logistiek", "spoedtransport"]),
  V("koeriers", "Koeriersdienst", "mobiliteit", "koerier", "Koeriers- en spoedservice", ["same day", "zakelijk", "internationaal"]),
  V("taxi", "Taxibedrijf", "mobiliteit", "taxichauffeur", "Taxi en groepsvervoer", ["luchthaven", "zorgvervoer", "zakelijk"]),
  V("privechauffeur", "Privéchauffeur", "mobiliteit", "chauffeur", "Privé- en directievervoer", ["airport transfer", "evenement", "zakelijk"]),
  V("rijschool", "Rijschool", "mobiliteit", "rijinstructeur", "Rijlessen en examenbegeleiding", ["proefles", "theorie", "scooterrijles"]),

  V("boekhouder", "Boekhouder", "zakelijk", "boekhouder", "Boekhouding en belasting", ["jaarrekening", "btw", "salarisadministratie"]),
  V("accountant", "Accountantskantoor", "zakelijk", "accountant", "Accountancy en advies", ["controle", "jaarrekening", "fiscaal advies"]),
  V("advocaat", "Advocatenkantoor", "zakelijk", "advocaat", "Juridisch advies en bijstand", ["ondernemingsrecht", "arbeidsrecht", "familierecht"]),
  V("notaris", "Notariskantoor", "zakelijk", "notaris", "Notariële dienstverlening", ["wonen", "ondernemen", "familie"]),
  V("hypotheek", "Hypotheekadviseur", "zakelijk", "hypotheekadviseur", "Hypotheek- en woonadvies", ["starter", "oversluiten", "verduurzamen"]),
  V("verzekeringen", "Verzekeringsadviseur", "zakelijk", "verzekeringsadviseur", "Verzekeringen en risicoadvies", ["particulier", "zakelijk", "schade"]),
  V("consultant", "Consultancybureau", "zakelijk", "consultant", "Strategie en organisatieadvies", ["transformatie", "proces", "groei"]),
  V("coach", "Coachingspraktijk", "zakelijk", "coach", "Coaching en ontwikkeling", ["loopbaan", "leiderschap", "persoonlijke groei"]),
  V("uitzendbureau", "Uitzendbureau", "zakelijk", "recruiter", "Werving en flexibel personeel", ["vacatures", "detachering", "payrolling"]),
  V("makelaar", "Makelaar", "zakelijk", "makelaar", "Woningverkoop en aankoop", ["waardebepaling", "taxatie", "verhuur"]),

  V("ict", "ICT-bedrijf", "digitaal", "ICT-specialist", "ICT-beheer en support", ["cloud", "cybersecurity", "werkplek"]),
  V("software", "Softwarebedrijf", "digitaal", "softwarepartner", "Softwareontwikkeling", ["webapp", "integratie", "saas"]),
  V("webshop", "Webshop", "digitaal", "webshopspecialist", "Online verkoop", ["e-commerce", "productadvies", "bezorging"]),
  V("marketing", "Marketingbureau", "digitaal", "marketingspecialist", "Online marketing en groei", ["seo", "advertising", "strategie"]),
  V("webdesign", "Webdesignbureau", "digitaal", "webdesigner", "Webdesign en ontwikkeling", ["website", "landingspagina", "onderhoud"]),
  V("cybersecurity", "Cybersecuritybedrijf", "digitaal", "securityspecialist", "Digitale beveiliging", ["pentest", "monitoring", "awareness"]),
  V("automation", "Automatiseringsbureau", "digitaal", "automatiseringsspecialist", "Procesautomatisering", ["ai", "integraties", "workflows"]),

  V("fotograaf", "Fotograaf", "media", "fotograaf", "Fotografie en beeldproductie", ["portret", "bedrijf", "evenement"]),
  V("videograaf", "Videograaf", "media", "videograaf", "Video en filmproductie", ["brandfilm", "social video", "evenement"]),
  V("drukkerij", "Drukkerij", "media", "drukspecialist", "Drukwerk en print", ["huisstijl", "signing", "verpakking"]),
  V("nieuws", "Nieuwsplatform", "media", "redactie", "Nieuws en achtergrond", ["lokaal nieuws", "interviews", "agenda"]),

  V("kapper", "Kapperssalon", "beauty", "kapper", "Knippen, kleuren en styling", ["dames", "heren", "bruidskapsel"]),
  V("barbier", "Barbershop", "beauty", "barbier", "Knippen en baardverzorging", ["fade", "hot towel", "styling"]),
  V("nagelstudio", "Nagelstudio", "beauty", "nagelstylist", "Nagelstyling en verzorging", ["gelnagels", "nail art", "BIAB"]),
  V("pedicure", "Pedicurepraktijk", "beauty", "pedicure", "Voetverzorging", ["medisch", "diabetes", "cosmetisch"]),
  V("manicure", "Manicurestudio", "beauty", "manicure", "Hand- en nagelverzorging", ["gellak", "spa manicure", "nail art"]),
  V("wimpers", "Wimperstudio", "beauty", "wimperstylist", "Wimper- en wenkbrauwbehandelingen", ["extensions", "lash lift", "brows"]),
  V("schoonheidssalon", "Schoonheidssalon", "beauty", "schoonheidsspecialist", "Huidverbetering en beauty", ["gezicht", "huidanalyse", "ontharen"]),
  V("sauna", "Sauna & Wellness", "beauty", "wellnessspecialist", "Sauna en wellness", ["opgieting", "arrangement", "spa"]),
  V("massage", "Massagepraktijk", "beauty", "massagetherapeut", "Massage en ontspanning", ["sportmassage", "ontspanning", "deep tissue"]),

  V("personal-trainer", "Personal Trainer", "sport", "personal trainer", "Persoonlijke training", ["kracht", "afvallen", "voeding"]),
  V("sportschool", "Sportschool", "sport", "fitnesscoach", "Fitness en groepslessen", ["fitness", "groepsles", "coaching"]),
  V("sportvereniging", "Sportvereniging", "sport", "vereniging", "Sport en verenigingsactiviteiten", ["lidmaatschap", "training", "competitie"]),
  V("voetbal", "Voetbalvereniging", "sport", "voetbalclub", "Voetbal en clubactiviteiten", ["jeugd", "senioren", "wedstrijd"]),
  V("tennis", "Tennisvereniging", "sport", "tennisclub", "Tennis en lessen", ["baanhuur", "training", "competitie"]),
  V("squash", "Squashcentrum", "sport", "squashcentrum", "Squash en baanhuur", ["les", "competitie", "arrangement"]),
  V("paardensport", "Manege & Paardensport", "sport", "paardensportspecialist", "Paardrijden en training", ["rijles", "pension", "wedstrijd"]),
  V("yogastudio", "Yogastudio", "sport", "yogadocent", "Yoga en mindfulness", ["groepsles", "retreat", "privéles"]),

  V("fysiotherapie", "Fysiotherapiepraktijk", "gezondheid", "fysiotherapeut", "Fysiotherapie en herstel", ["sport", "manueel", "revalidatie"]),
  V("hypnotherapie", "Hypnotherapiepraktijk", "gezondheid", "hypnotherapeut", "Hypnotherapie en coaching", ["stress", "gewoonten", "zelfvertrouwen"]),
  V("holistisch", "Holistische Praktijk", "gezondheid", "holistisch therapeut", "Holistische begeleiding", ["healing", "ademwerk", "energie"]),
  V("tandarts", "Tandartspraktijk", "gezondheid", "tandarts", "Mondzorg en tandheelkunde", ["controle", "preventie", "cosmetisch"]),
  V("psycholoog", "Psychologenpraktijk", "gezondheid", "psycholoog", "Psychologische begeleiding", ["diagnostiek", "therapie", "coaching"]),
  V("dietist", "Diëtistenpraktijk", "gezondheid", "diëtist", "Voedingsadvies en leefstijl", ["afvallen", "medisch", "sport"]),
  V("verloskundige", "Verloskundigenpraktijk", "gezondheid", "verloskundige", "Zwangerschapsbegeleiding", ["controle", "echo", "kraamtijd"]),
  V("dierenarts", "Dierenartsenpraktijk", "gezondheid", "dierenarts", "Diergeneeskundige zorg", ["consult", "vaccinatie", "operatie"]),

  V("restaurant", "Restaurant", "horeca", "restaurateur", "Lunch en diner", ["menu", "private dining", "groepen"]),
  V("pizzeria", "Pizzeria", "horeca", "pizzabakker", "Pizza en Italiaanse gerechten", ["afhalen", "bezorgen", "diner"]),
  V("snackbar", "Snackbar", "horeca", "horecaondernemer", "Snacks en maaltijden", ["afhalen", "bezorgen", "catering"]),
  V("sushi", "Sushirestaurant", "horeca", "sushichef", "Sushi en Japanse gerechten", ["all-you-can-eat", "afhalen", "bezorgen"]),
  V("doner", "Dönerzaak", "horeca", "horecaondernemer", "Döner en grillgerechten", ["afhalen", "bezorgen", "menu"]),
  V("cafe", "Café", "horeca", "café-eigenaar", "Dranken en gezelligheid", ["borrel", "lunch", "evenement"]),
  V("hotel", "Hotel", "horeca", "hotelier", "Overnachtingen en arrangementen", ["kamers", "ontbijt", "zakelijk"]),
  V("catering", "Cateringbedrijf", "horeca", "cateraar", "Catering en evenementen", ["bedrijf", "bruiloft", "buffet"]),

  V("camping", "Camping", "recreatie", "campinghouder", "Kamperen en verblijf", ["staanplaats", "accommodatie", "faciliteiten"]),
  V("festival", "Festival", "recreatie", "festivalorganisatie", "Festival en tickets", ["programma", "tickets", "praktisch"]),
  V("bootverhuur", "Bootverhuur", "recreatie", "bootverhuurder", "Bootverhuur en arrangementen", ["sloep", "route", "groepen"]),
  V("paintball", "Paintballcentrum", "recreatie", "paintballorganisator", "Paintball en groepsuitjes", ["bedrijfsuitje", "vrienden", "kinderfeest"]),
  V("lasergame", "Lasergamecentrum", "recreatie", "lasergameorganisator", "Lasergame en arrangementen", ["groepen", "feestje", "bedrijf"]),
  V("escape-room", "Escape Room", "recreatie", "escape-roomorganisator", "Escape rooms en groepen", ["teamuitje", "vrienden", "cadeaubon"]),
  V("evenementenlocatie", "Evenementenlocatie", "recreatie", "locatiemanager", "Locatieverhuur en events", ["bruiloft", "bedrijf", "feest"]),

  V("elektronica", "Elektronicawinkel", "retail", "elektronicaspecialist", "Elektronica en advies", ["computer", "audio", "reparatie"]),
  V("fashion", "Modewinkel", "retail", "modespecialist", "Mode en styling", ["dames", "heren", "accessoires"]),
  V("bloemist", "Bloemist", "retail", "bloemist", "Bloemen en boeketten", ["bezorgen", "bruiloft", "abonnement"]),
  V("juwelier", "Juwelier", "retail", "juwelier", "Sieraden en horloges", ["trouwringen", "reparatie", "taxatie"]),
  V("opticien", "Opticien", "retail", "opticien", "Brillen en oogzorg", ["oogmeting", "contactlenzen", "zonnebril"]),
  V("meubelwinkel", "Meubelwinkel", "retail", "interieurspecialist", "Meubels en interieuradvies", ["banken", "tafels", "maatwerk"]),
  V("lokale-specialist", "Lokale Specialist", "lokaal", "specialist", "Lokale dienstverlening", ["advies", "uitvoering", "onderhoud"])
];
