const { createHash } = require("crypto");
const { createJourneyRepository } = require("../repository");
const { createJourneyLogger } = require("../logger");
const { validateMailCommand } = require("../mail/command");
const { resolvePaymentPaidOwnership } = require("./ownershipResolver");
const { planPaymentPaidProgress } = require("./progressTransition");
const { createPaymentPaidRepository } = require("./repository");
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function createPaymentPaidService(options = {}) { const env = options.env || process.env; const journeyRepository = options.journeyRepository || createJourneyRepository(options); const paymentRepository = options.paymentRepository || createPaymentPaidRepository(options); const log = options.log || createJourneyLogger({ logger: options.logger, component: "payment_paid_ownership" }); return { dispatch: (input) => dispatch(input, env, journeyRepository, paymentRepository, log) }; }
async function dispatch(input = {}, env, journeyRepository, paymentRepository, log) {
  const legacy = typeof input.legacySend === "function" ? input.legacySend : async () => null;
  const customerId = text(input.customerId); const invoiceId = text(input.invoiceId); const paymentReference = text(input.paymentContext?.paymentReference); const recipient = text(input.recipient);
  if (!recipient) return legacyResult(legacy, "recipient_missing");
  if (!UUID.test(customerId) || !UUID.test(invoiceId) || !paymentReference) return legacyResult(legacy, "stable_payment_scope_missing");
  const runtimeEnvironment = runtime(env); const paymentContext = input.paymentContext || {};
  const preflight = resolvePaymentPaidOwnership({ ...input, customerId, paymentReference, paymentContext, runtimeEnvironment, journeyInstance: null, transition: null }, env);
  if (preflight.reason !== "test_journey_missing") return legacyResult(legacy, preflight.reason);
  let lookup; try { lookup = await paymentRepository.findTestJourney(customerId); } catch { lookup = { available: false, reason: "storage_read_failed" }; }
  if (!lookup?.available) return legacyResult(legacy, lookup?.reason || "storage_unavailable");
  const reference = fingerprint(paymentReference); const transition = planPaymentPaidProgress(lookup.row || {}, reference, paymentContext);
  const ownership = resolvePaymentPaidOwnership({ ...input, customerId, paymentReference, paymentContext, runtimeEnvironment, journeyInstance: lookup.row, transition }, env);
  const keys = stableKeys({ provider: paymentContext.provider, paymentReference, customerId, orderReference: paymentContext.orderReference, invoiceId, templateVersion: 1 });
  if (ownership.owner !== "journey") return ownership.owner === "none" ? base("none", ownership.reason) : legacyResult(legacy, ownership.reason);
  let command;
  try { command = validateMailCommand({ automationKey: "journey.payment_paid", templateKey: "journey.payment_paid", templateVersion: 1, journeyEventKey: keys.eventKey, outboxIdempotencyKey: keys.outboxKey, customerReference: customerId, journeyInstanceReference: lookup.row.id, recipient, replyToProfile: { email: text(input.replyTo) || "info@maxwebstudio.nl" }, subjectData: { label: text(input.invoiceLabel) || "Betaling" }, templateData: { firstName: text(input.firstName), paymentReference: reference, invoiceLabel: text(input.invoiceLabel) || "uw betaling", paymentType: paymentContext.paymentType, paidAmountMinor: paymentContext.amountReliable ? paymentContext.paidAmountMinor : null, currency: paymentContext.amountReliable ? paymentContext.currency : "", percentage: transition.after.percentage, currentPhase: transition.after.currentPhase || "Projectstart", nextStep: copyFor(paymentContext.nextStepType), contactName: text(input.contactName) || "Team Max Webstudio" }, actionUrl: paymentContext.cta || "https://maxwebstudio.nl/klantportaal.html", metadata: { scenario: "payment_paid_test_customer", paymentReference: reference } }, { customerId, journeyInstanceId: lookup.row.id, environment: "test" }, env); } catch (error) { log.info("payment_validation_fallback", { operation: "payment_paid_dispatch", result: "legacy", owner: "legacy", errorCategory: code(error), testMode: true }); return legacyResult(legacy, code(error)); }
  let reminders = { cancelledCount: 0, reason: "reminder_cancellation_not_attempted" }; try { reminders = await paymentRepository.cancelPendingReminders({ safe: paymentContext.reminderScopeSafe === true, customerId, invoiceReference: paymentContext.invoiceReference, orderReference: paymentContext.orderReference }); } catch { reminders = { cancelledCount: 0, reason: "reminder_cancellation_failed" }; }
  try {
    const stored = await journeyRepository.recordJourneyEvent({ eventKey: keys.eventKey, eventType: "payment.paid", entityType: "invoice", entityId: invoiceId, customerId, journeyInstanceId: lookup.row.id, environment: "test", occurredAt: safeDate(input.paidAt), payload: safePayload(paymentContext, reference, transition, ownership.reason, reminders.cancelledCount) }, { context: { customerId, journeyInstanceId: lookup.row.id, journeyKey: lookup.row.instance_key, entityId: invoiceId, environment: "test" }, outbox: { idempotencyKey: keys.outboxKey, effectType: "email.payment_paid", payload: { mailCommand: command, ...safePayload(paymentContext, reference, transition, ownership.reason, reminders.cancelledCount) } } });
    if (!stored?.available) return legacyResult(legacy, stored?.reason || "storage_unavailable");
    if (!stored?.row?.outbox_id) throw Object.assign(new Error("outbox unavailable"), { code: "outbox_not_created" });
    let progress = { updated: false, reason: transition.duplicate ? "duplicate_progress" : "progress_not_attempted" }; try { const update = await paymentRepository.applyProgress(lookup.row, transition); progress = { updated: Boolean(update?.available && !update?.skipped), reason: update?.reason || "progress_write_failed" }; } catch { progress.reason = "progress_write_failed"; }
    return { ...base("journey", stored.row.duplicate ? "duplicate_suppressed" : "journey_outbox_accepted"), durable: true, fallbackAllowed: false, duplicate: Boolean(stored.row.duplicate), eventKey: keys.eventKey, outboxId: stored.row.outbox_id, paymentReference: reference, progress, reminders };
  } catch (error) { log.error("payment_journey_enqueue_failed", { operation: "payment_paid_dispatch", result: "failed", owner: "journey", errorCategory: code(error), testMode: true }); return { ...base("journey", "journey_enqueue_ambiguous_no_legacy"), fallbackAllowed: false, failed: true, eventKey: keys.eventKey, paymentReference: reference }; }
}
function safePayload(context, reference, transition, ownershipReason, reminderCancelledCount = 0) { return { source: "mollie_webhook", testMode: true, ownership: "journey", ownershipReason, providerCategory: context.provider, paymentEnvironment: context.environment, paymentReference: reference, orderReference: text(context.orderReference), invoiceReference: text(context.invoiceReference), journeyType: context.journeyType, paymentType: context.paymentType, paymentState: context.paymentState, invoiceState: context.invoiceState, commercialCompletionState: context.commercialCompletionState, paidComponent: context.paidComponent, remainingComponent: context.remainingComponent, nextStepType: context.nextStepType, customerActionRequired: context.customerActionRequired === true, internalActionRequired: context.internalActionRequired === true, progressBefore: transition.before.percentage, progressAfter: transition.after.percentage, reminderCancelledCount: Math.max(0, Number(reminderCancelledCount) || 0) } }
function stableKeys({ provider, paymentReference, customerId, orderReference, invoiceId, templateVersion }) { const scope = hash(`${provider}:${paymentReference}:${customerId}:${orderReference || invoiceId}:email.payment_paid:v${templateVersion}`); return { eventKey: `payment.paid:${scope}`, outboxKey: `payment.paid.email:${scope}:v${templateVersion}` }; }
function copyFor(type) { return ({ project_onboarding: "Uw project en onboarding kunnen nu volgens de bestaande afspraak verder.", project_start: "Wij verwerken de betaling en zetten de volgende projectstap klaar.", technical_delivery: "De commerciële betaling is compleet; wij gaan verder met de technische oplevering.", invoice_complete: "De gekoppelde factuur is voldaan. U hoeft voor deze factuur niets meer te doen." })[type] || "Team Max Webstudio controleert de vervolgstap."; }
async function legacyResult(fn, reason) { await fn(); return base("legacy", reason); }
function base(owner, reason) { return { owner, reason, durable: false, eligibility: owner === "journey" ? "eligible" : "ineligible", fallbackAllowed: owner === "legacy", duplicate: false, failed: false, testMode: true, eventKey: null }; }
function safeDate(value) { const date = new Date(value || Date.now()); return Number.isNaN(date.getTime()) ? new Date().toISOString() : date.toISOString(); }
function runtime(env) { return [env.APP_ENV, env.APP_ENVIRONMENT, env.CONTEXT, env.NETLIFY_ENV].some((value) => ["prod", "production"].includes(text(value).toLowerCase())) ? "production" : "test"; }
function fingerprint(value) { return hash(value).slice(0, 16); } function hash(value) { return createHash("sha256").update(String(value || "")).digest("hex").slice(0, 40); }
function code(error) { return text(error?.code || error?.name || "payment_dispatch_failed").replace(/[^a-z0-9_.-]/gi, "_").slice(0, 80).toLowerCase(); }
function text(value) { return String(value || "").trim(); }
module.exports = { createPaymentPaidService, _private: { fingerprint, stableKeys } };
