const { createHash } = require("crypto");
const { parseAllowlist, resolveJourneyFeatureFlag } = require("../featureFlags");
const { FEATURE_FLAGS } = require("../types");
const { createJourneyRepository } = require("../repository");
const { createJourneyLogger } = require("../logger");
const { runNetworkCheck } = require("./networkCheck");
const { planPostLaunchProgress } = require("./progressTransition");
const { resolveReviewEligibility } = require("./reviewEligibility");
const { createTimelineEvent } = require("../../services/timelineService");
const { createPostLaunchRepository } = require("./repository");
function createPostLaunchCheckService(options = {}) {
  const env = options.env || process.env; const repository = options.repository || createPostLaunchRepository({ env, fetchImpl: options.fetchImpl }); const journeyRepository = options.journeyRepository || createJourneyRepository({ env, fetchImpl: options.fetchImpl }); const checker = options.checker || ((website) => runNetworkCheck(website, { fetchImpl: options.fetchImpl, lookup: options.lookup })); const log = options.log || createJourneyLogger({ logger: options.logger, component: "post_launch_check" }); const notify = options.notify || defaultNotify;
  return { run: (input) => run({ input, env, repository, journeyRepository, checker, log, notify, now: options.now }) };
}
async function run({ input = {}, env, repository, journeyRepository, checker, log, notify, now }) {
  const customerId = text(input.customerId), websiteId = text(input.websiteId); const runtime = runtimeEnvironment(env); const context = { environment: runtime, customerId, adminAuthorized: input.adminAuthorized === true, scopeKey: "post-launch-check" };
  const engine = resolveJourneyFeatureFlag(FEATURE_FLAGS.JOURNEY_ENGINE_ENABLED, context, env); const selected = parseAllowlist(env.JOURNEY_POST_LAUNCH_CHECK_TEST_CUSTOMERS);
  if (!input.adminAuthorized || !engine.enabled || !selected.has(customerId)) return base("disabled", !input.adminAuthorized ? "admin_authorization_required" : !engine.enabled ? engine.reason : "customer_not_selected_for_post_launch_check");
  const scope = await repository.loadScope(customerId, websiteId); if (!scope.available || !scope.row) return base("unavailable", scope.reason);
  const { customer, website, project, instance, healthWebsite, maintenanceSubscription } = scope.row;
  const publication = text(project.metadata?.previewReview?.livePublicationReference || project.metadata?.livePublicationReference || website.metadata?.livePublicationReference || website.last_deploy_at); const host = hostname(website.live_url || website.domain); if (!publication || !host) return base("unavailable", "live_publication_scope_missing");
  const version = "post_launch.v1"; const checkKey = hash(`${customer.id}:${website.id}:${publication}:${host}:technical:${version}`); const attempt = Number(instance.metadata?.postLaunchCheck?.attempt || 0) + 1; const runKey = `${checkKey}:${attempt}`; const checkedAt = new Date(typeof now === "function" ? now() : Date.now()).toISOString();
  if (instance.metadata?.postLaunchCheck?.activeRunKey) return base("duplicate", "post_launch_check_already_active");
  const claim = await repository.claimRun(instance, runKey, checkedAt); if (!claim.row) return base("duplicate", claim.reason || "post_launch_claim_conflict");
  try { await record(journeyRepository, "website.post_launch_check_started", `${runKey}:started`, scope.row, { checkVersion: version, checkKey, attempt }, context); }
  catch (error) {
    await repository.finalizeRun(claim.row, { patch: null }, { checkVersion: version, checkKey, attempt, overallResult: "inconclusive", internalActionRequired: false, retryEligible: true, reviewMailStatus: "not_scheduled", reasonCodes: [safeCode(error)], checkedAt }).catch(() => null);
    log.error("post_launch_start_event_failed", { action: "post_launch_check", result: "inconclusive", errorCategory: safeCode(error), environment: "test" });
    return base("unavailable", "post_launch_start_event_failed");
  }
  let network; try { network = await checker(website); } catch (error) { network = { liveUrlState: "unconfirmed", httpsState: "unknown", dnsState: "unknown", sslState: "not_checked", responseState: "check_service_error", redirectState: "none", basicContentState: "unchecked", reasonCodes: [safeCode(error)] }; }
  const portalLinkageState = customer.id === website.customer_id && project.customer_id === customer.id && project.website_id === website.id && instance.customer_id === customer.id && instance.project_id === project.id ? "matching" : "mismatch";
  const maintenanceState = maintenanceSubscription?.status === "active" ? "active" : maintenanceSubscription ? "planned" : project.metadata?.websiteCommercialOrder?.maintenanceCode && project.metadata.websiteCommercialOrder.maintenanceCode !== "none" ? "selected_not_activated" : "not_selected";
  const overallResult = overall(network, portalLinkageState); const internalActionRequired = overallResult === "attention_required"; const retryEligible = overallResult === "inconclusive";
  const timing = { earliestCheckTime: checkedAt, lastCheckedAt: checkedAt, nextEligibleCheckAt: retryEligible ? new Date(new Date(checkedAt).getTime() + 3600000).toISOString() : null, reviewEligibleAfter: new Date(new Date(project.metadata?.previewReview?.liveAt || checkedAt).getTime() + bounded(env.JOURNEY_REVIEW_ELIGIBILITY_DAYS, 7, 1, 90) * 86400000).toISOString() };
  const result = { websiteReference: website.id, checkVersion: version, environment: "test", liveAt: text(project.metadata?.previewReview?.liveAt), hostnameFingerprint: hash(host).slice(0, 16), ...network, portalLinkageState, maintenanceState, overallResult, internalActionRequired, reasonCodes: [...new Set([...(network.reasonCodes || []), ...(portalLinkageState === "mismatch" ? ["portal_linkage_mismatch"] : [])])].slice(0, 10), checkedAt, retryEligible, reviewMailStatus: "not_scheduled", attempt, checkKey, ...timing };
  const transition = planPostLaunchProgress(claim.row, result); if (!transition.valid) { result.overallResult = "inconclusive"; result.internalActionRequired = false; result.retryEligible = true; result.reasonCodes.push(transition.reason); }
  const effectiveTransition = transition.valid ? transition : planPostLaunchProgress(claim.row, { ...result, overallResult: "inconclusive" });
  result.progressBefore = effectiveTransition.before.percentage; result.progressAfter = effectiveTransition.after.percentage;
  result.reviewEligibility = resolveReviewEligibility({ liveAt: project.metadata?.previewReview?.liveAt, overallResult: result.overallResult, internalActionRequired: result.internalActionRequired, journeyCompleted: effectiveTransition.after.complete, hasPostLaunchCheck: true, reviewAlreadyRequested: project.metadata?.previewReview?.postLaunch?.reviewScheduled === true, reviewAlreadyReceived: project.metadata?.reviewReceived === true }, { now: checkedAt, minimumDays: env.JOURNEY_REVIEW_ELIGIBILITY_DAYS });
  const saved = await repository.finalizeRun(claim.row, effectiveTransition, result); if (!saved.row) return base("unavailable", saved.reason || "post_launch_finalize_conflict");
  const eventType = result.overallResult === "attention_required" ? "website.post_launch_attention_required" : "website.post_launch_check_completed";
  const event = await record(journeyRepository, eventType, `${checkKey}:${eventType}`, { ...scope.row, instance: saved.row }, safePayload(result), context);
  if (result.internalActionRequired) {
    try { await notify({ customerId, websiteId, projectId: project.id, checkKey, reasonCodes: result.reasonCodes }); }
    catch (error) { log.error("post_launch_notification_failed", { action: "post_launch_check", result: result.overallResult, errorCategory: safeCode(error), environment: "test" }); }
  }
  log.info("post_launch_check_completed", { action: "post_launch_check", result: result.overallResult, environment: "test", checkVersion: version, internalActionRequired });
  return { success: true, testMode: true, duplicate: Boolean(event?.row?.duplicate), result };
}
async function record(repo, eventType, eventKey, scope, payload, context) { return repo.recordJourneyEvent({ eventKey, eventType, entityType: "website", entityId: scope.website.id, customerId: scope.customer.id, journeyInstanceId: scope.instance.id, environment: "test", occurredAt: new Date().toISOString(), payload }, { context }); }
async function defaultNotify(input) { return createTimelineEvent({ eventType: "health_warning", title: "Nazorgcontrole vraagt aandacht", description: `Technische nazorgcontrole: ${input.reasonCodes.join(", ")}.`, module: "journey_post_launch", referenceType: "website", referenceId: input.websiteId, customerId: input.customerId, severity: "warning", isGlobal: true, actorName: "Journey Engine", actorRole: "automation", metadata: { dedupeKey: `post_launch_attention:${input.checkKey}`, projectId: input.projectId, reasonCodes: input.reasonCodes } }); }
function overall(network, linkage) { if (linkage !== "matching") return "attention_required"; if (["timeout", "dns_failure", "network_failure", "check_service_error", "response_read_failed", "unexpected_http_status"].includes(network.responseState)) return "inconclusive"; if (network.responseState === "success" || network.responseState === "redirect_success") return network.basicContentState === "html" ? "healthy" : "attention_required"; return "attention_required"; }
function safePayload(result) { return { checkVersion: result.checkVersion, checkKey: result.checkKey, liveAt: result.liveAt, hostnameFingerprint: result.hostnameFingerprint, overallResult: result.overallResult, liveUrlState: result.liveUrlState, httpsState: result.httpsState, dnsState: result.dnsState, sslState: result.sslState, responseState: result.responseState, redirectState: result.redirectState, basicContentState: result.basicContentState, portalLinkageState: result.portalLinkageState, maintenanceState: result.maintenanceState, internalActionRequired: result.internalActionRequired, retryEligible: result.retryEligible, reviewEligibilityState: result.reviewEligibility.state, reviewMailStatus: "not_scheduled", progressBefore: result.progressBefore, progressAfter: result.progressAfter, reasonCodes: result.reasonCodes }; }
function base(status, reason) { return { success: false, testMode: true, status, reason }; } function hostname(value) { try { return new URL(/^https:/i.test(text(value)) ? text(value) : `https://${text(value)}`).hostname.toLowerCase(); } catch { return ""; } } function hash(value) { return createHash("sha256").update(value).digest("hex").slice(0, 40); } function safeCode(error) { return text(error?.code || error?.name || "post_launch_check_failed").replace(/[^a-z0-9_.-]/gi, "_").toLowerCase().slice(0, 80); } function bounded(value, fallback, min, max) { const n = Number(value); return Number.isFinite(n) ? Math.max(min, Math.min(max, Math.round(n))) : fallback; } function runtimeEnvironment(env) { return [env.APP_ENV, env.APP_ENVIRONMENT, env.CONTEXT, env.NETLIFY_ENV].some((v) => ["production", "prod"].includes(text(v).toLowerCase())) ? "production" : "test"; } function text(value) { return String(value || "").trim(); }
module.exports = { createPostLaunchCheckService, _private: { overall, safePayload } };
